# Generated by Django 5.1.7 on 2025-04-01 22:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("lote", models.CharField(max_length=50)),
                ("validade", models.DateField()),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("comum", "Comum"),
                            ("controlado", "Controlado"),
                            ("emergencia", "Carrinho de Emergencia"),
                        ],
                        default="comum",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaidaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("data_saida", models.DateTimeField(default=django.utils.timezone.now)),
                ("destino", models.CharField(max_length=100)),
                ("foi_para_emergencia", models.BooleanField(default=False)),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmacia.medicamento",
                    ),
                ),
            ],
        ),
    ]
